apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
spec:
  replicas: 1
  selector:
    matchLabels:
      name: 
  template:
    metadata:
      labels:
        name: 
    spec:
      containers:
        - name: 
          image: minio/minio:latest
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - data

--- 
apiVersion: v1
kind: Service
metadata:
  name: _service
spec:
  selector:
    name: 
  ports:
    - protocol: TCP
      port: 
      targetPort: 